language: php

php:
  - 7.1
  - 7.2
sudo: false

install: 
    cd src/
    travis_retry composer install --no-interaction --prefer-source

script: /src/vendor/bin/phpunit

notifications:
  email: false